{
 "title": "New dashboard",
 "time": { "from": "2024-05-23T14:14:58.220Z", "to": "2024-05-23T21:30:24.757Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Number of Visits on Each Minute",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT toStartOfMinute(timestamp) as time, count(*) as visit FROM \"default\".\"clickstream\" GROUP BY time ORDER BY time ASC;"
    }
   ]
  },
  {
   "title": "Most Visited Products",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    page_title,\r\n    COUNT(*) AS visits\r\nFROM clickstream\r\nWHERE page_url LIKE '/product_details/%'\r\nGROUP BY page_title\r\nORDER BY visits DESC\r\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Most Visited Pages",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    page_title,\r\n    COUNT(*) AS visits\r\nFROM clickstream\r\nGROUP BY page_title\r\nORDER BY visits DESC\r\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Most Visited Categories",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    page_title,\r\n    COUNT(*) AS visits\r\nFROM clickstream\r\nWHERE page_url LIKE '/categories/%'\r\nGROUP BY page_title\r\nORDER BY visits DESC\r\nLIMIT 10;"
    }
   ]
  }
 ]
}